name: Java CI with Gradle

on:
  push:
    branches: [ dev, feature/* ]
  pull_request:
    branches: [ dev, master ]
  release:
    types: [created]
  inputs:
    description: Run Job Manually
    required: false
    default: false

#permissions:
  #contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - run: echo ${{github.ref}}
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build And Test
        if: ${{contains(github.ref, 'master'}}
        run: gradle clean build
      #- name: Publish to GitHub Packages
       # run: gradle publish
        #env:
         # USERNAME: ${{ github.actor }}
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}
